#docker-compose.yaml

version: '3.8'

services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_INSTANCE}
    volumes:
        - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: "pg_isready -h db"
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: app
      dockerfile: Dockerfile
      args:
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql+asyncpg://${PG_USER}:${PG_PASSWORD}@db:${DB_PORT}/${PG_INSTANCE}
  front:
    build:
      context: front
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./front/neuro/media:/front/neuro/public/media
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
volumes:
  pgdata: