version: '3'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5433/dockert
    ports:
      - "8000:8000"

  db:
      image: postgres:15-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5433
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Bright#1270
        - POSTGRES_DB=dockert

volumes:
      postgres_data: 